# Generated by Django 3.0.6 on 2020-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_producto_unidadmedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
