# Generated by Django 3.0.6 on 2020-06-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasdet',
            name='costo',
        ),
    ]
