# Generated by Django 3.0.6 on 2020-06-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_facturadet_facturaenc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
